### ISSUE TITLE
[CONTENT] Missing links to respective pre-filtered site versions on minf-info and musk-info pages

### ISSUE THREAD

**Issue by cody0-0** [cody0-0/jahresprojekt#104]
There should be links to the pre-filtered (& colored) site versions on the minf and musk info-pages.
(Should be rather near the top)

**Comment by duevil** [comment]
> There should be links to the pre-filtered (& colored) site versions on the minf and musk info-pages. (Should be rather near the top)

Wäre es nicht sinnvoller den Link im entsprechenden Sinnabschnitt zu setzten? Wäre halt aktuell das Ende der Seite, aber der Punkt ist ja so gesehen über das Menü am Anfang erreichbar
