### ISSUE TITLE
[BUG] weird and missing spacings

### ISSUE THREAD

**Issue by cody0-0** [cody0-0/jahresprojekt#19]
## Describe the bug
There are some spacings that are just too small.

## To Reproduce
1. Open the website
2. Look at spacing on narrow mobile version
3. Look at spacing between news block and filters (mobile is much worse than desktop)

## Expected behavior
Between sections should be more (maybe double) the spacing than between other elements

## Specifications
**Desktop (please complete the following information):**
 - OS: macOS 14.4.1 & Windows
 - Browser Arc (Chromium), Chrome
 - Latest

**Comment by duevil** [comment]
Logo in Header
