### ISSUE TITLE
[FEATURE] Gallery on Beitrags-Page

### ISSUE THREAD

**Issue by duevil** [cody0-0/jahresprojekt#32]
## Short feature description:

Add the gallery after the main content on the Beitrag page
- when more images are available than can be shown, add black image with overflown image number
- desktop: max 6 images in one row
- mobile: max 4 images in two rows
- tablet: max 4 imgages in one row

@cody0-0: Visuals (including black box)
@duevil: script (choosing images, counting overflow and toggleing)

**Comment by cody0-0** [comment]
Visuals sollte ready sein

**Comment by duevil** [comment]
auch hier: @cody0-0 wie ist der Stand hierbei? Wollen wir das schonmal in Master mergen oder soll das dann in der Branch für #80 gemerged werden?

**Comment by cody0-0** [comment]
Hab mich mal nochmal an das visuelle des +x Elements gesetzt..

**Meine Tendenz: entweder der Mix aus 3 und 5; oder Nr. 6.**
Dazu: Ich bevorzuge die "Light" Variante der Schrift und für die Fälle in denen die Zahl in der unteren rechten Kachel steht: Hier wird es sehr knapp, sobald "+${zahl}" 2-stellig wird.

Bisher:
<img width="862" alt="image" src="https://github.com/cody0-0/jahresprojekt/assets/113670708/c694b9f6-a5b4-4905-99a5-7397edbbbb22">

Neu 1 (Textfarbe)
<img width="862" alt="image" src="https://github.com/cody0-0/jahresprojekt/assets/113670708/9bae66f9-58c8-4caf-9149-7ad0d9dc4c4f">

Neu 2 (größere Schrift, impliziertes +, einheitlich wirkende Linienstärken)
<img width="862" alt="image" src="https://github.com/cody0-0/jahresprojekt/assets/113670708/7385c0f4-5333-4f8b-8d24-66cc9ff0c6dc">

Neu 3 (angedeutetes +)
<img width="862" alt="image" src="https://github.com/cody0-0/jahresprojekt/assets/113670708/e8b70941-7544-4aa4-bd2b-2df5f584f491">

Neu 4 (nur Text)
<img width="862" alt="image" src="https://github.com/cody0-0/jahresprojekt/assets/113670708/f42a0c42-89ee-49d3-9403-9d7f8e5f965f">
<img width="862" alt="image" src="https://github.com/cody0-0/jahresprojekt/assets/113670708/dec662bd-9c93-4015-80f5-c3d522e45854">
<img width="862" alt="image" src="https://github.com/cody0-0/jahresprojekt/assets/113670708/7a2c02a0-8433-4fc0-8caa-18a30445ded0">
<img width="862" alt="image" src="https://github.com/cody0-0/jahresprojekt/assets/113670708/f2842e6e-fa44-444c-ad05-2809accde686">

Neu 5 (abgedunkeltes Bild)
<img width="862" alt="image" src="https://github.com/cody0-0/jahresprojekt/assets/113670708/43fa0157-3771-4816-b80c-5312cfdae78a">
<img width="862" alt="image" src="https://github.com/cody0-0/jahresprojekt/assets/113670708/5d8ac91c-990d-4e15-a3e2-223524908cc1">

Neu 6 (mehrere Bilder)
<img width="801" alt="image" src="https://github.com/cody0-0/jahresprojekt/assets/113670708/d62d09a0-6342-43a6-a0a6-4083116cc6ec">
<img width="801" alt="image" src="https://github.com/cody0-0/jahresprojekt/assets/113670708/7b4f1f0b-6457-4365-8441-b99a0732a08d">

**Comment by cody0-0** [comment]
Um das endlich aus dem weg zu Räumen: Version 5.1 ist jetzt gepusht.
Version 5.2 ist ein commit davor.
Version 6 würde in einer unverbugten Version mehr Zeit in Anspruch nehmen und wurde daher vorerst nicht gebaut/committed.
PR folgt.

**Comment by duevil** [comment]
> Um das endlich aus dem weg zu Räumen: Version 5.1 ist jetzt gepusht. Version 5.2 ist ein commit davor. Version 6 würde in einer unverbugten Version mehr Zeit in Anspruch nehmen und wurde daher vorerst nicht gebaut/committed. PR folgt spätestens mit PR von #80.

Alles klar, dann merge ich den in den Branch für #80

**Comment by duevil** [comment]
@cody0-0 wie funktioniert das Erkennen der Anzahl von weiteren Bildern in der Galerie? Werden die einfach alle das 'content-gallery'-div geklatscht?
