### ISSUE TITLE
[FEATURE] Further Beitrag previews on Beitrags-Page

### ISSUE THREAD

**Issue by duevil** [cody0-0/jahresprojekt#33]
## Short feature description:

Implementation of three (two on tablet) further Beiträge on the bottom of the Beitrags-page

@cody0-0: visuals
@duevil: script (randomly choosing a Beitrag)

**Comment by cody0-0** [comment]
Visuals sollten vorerst bereit sein.

Spacings (vertical) werden mit #19 berichtigt.

Das Styling is so aufgebaut, dass die typischen ".preview"-Elemente erwartet werden und deren Styling angepasst wird. Wrapping Container der Empfehlungen ist "#recommendation-container".

**Comment by duevil** [comment]
@cody0-0 wie ist der Stand hierbei? Wollen wir das schonmal in Master mergen oder soll das dann in der Branch für #80 gemerged werden?

**Comment by cody0-0** [comment]
> @cody0-0 wie ist der Stand hierbei? Wollen wir das schonmal in Master mergen oder soll das dann in der Branch für #80 gemerged werden?

Kommt darauf an - wenn du meinst, #80 ist relativ schnell fertig, dann fänd ichs besser, wenn es direkt mit Funktionalität in Master geht, ansonsten würd ichs mergen spätestens sobald ich mich an die Spacings setze -> also wharscheinlich irgendwann heut Abend.

**Comment by duevil** [comment]
> > @cody0-0 wie ist der Stand hierbei? Wollen wir das schonmal in Master mergen oder soll das dann in der Branch für #80 gemerged werden?
> 
> Kommt darauf an - wenn du meinst, #80 ist relativ schnell fertig, dann fänd ichs besser, wenn es direkt mit Funktionalität in Master geht, ansonsten würd ichs mergen spätestens sobald ich mich an die Spacings setze -> also wharscheinlich irgendwann heut Abend.

Joa, obs schnell fertig wird kann ich nicht sagen, aber denke ich mal, da das dann eigentlich nur Javascript ist, was auf jeden Fall einfacher ist als in CSS rum zu experimentieren.

Wollen wir sonst erstmal alles, was wir aktuell diesbezüglich haben, in einen Branch (muss ja nicht Master sein) mergen, damit ich zumindest die Basen von allem haben und auf denen das Script aufbauen kann?

**Comment by duevil** [comment]
Jo genau
