### ISSUE TITLE
[BUG] Resource Files not found when using GH Pages

### ISSUE THREAD

**Issue by cody0-0** [cody0-0/jahresprojekt#60]
## Describe the bug

Resource Files (as far as I've seen - only the .json-Files) are not found when viewing the website via Github Pages.

## To Reproduce

Open https://cody0-0.github.io/jahresprojekt/

Error:
Failed to load resource: the server responded with a status of 404 ([resources/news.json:1](https://cody0-0.github.io/resources/news.json))

Failed to load resource: the server responded with a status of 404 ([resources/content.json:1](https://cody0-0.github.io/resources/content.json))

Locally the files are found.

## Expected behavior

Resources should be found. 
Resources are under 
- https://cody0-0.github.io/jahresprojekt/resources/news.json
- https://cody0-0.github.io/jahresprojekt/resources/content.json

The query is addressed at cody0-0.github.io/resources/file.json, though...

**Comment by duevil** [comment]
Completed with [7a9c7e4](a820d2a0decf19cc2d63a515fcaf0e55d21e697f)
