### ISSUE TITLE
[BUG] No filtering via site and course simultaniously

### ISSUE THREAD

**Issue by cody0-0** [cody0-0/jahresprojekt#76]
## Describe the bug

When visiting the site from a Studengang-specific url (site=("minf"|"musk")) the Studiengangs-Filter are not working correctly.

## Expected behavior

When visiting the page on any site the all filter should be togglable.
When joining on a Studiengangs-specific site the corresponding course-filter should be set active instead of filtering seperately.

**Comment by duevil** [comment]
Will be fixed when resolving #51

**Comment by duevil** [comment]
Will be resolved either with #85 or when resolving #8
