### ISSUE TITLE
[FEATURE] previews-grid filter

### ISSUE THREAD

**Issue by cody0-0** [cody0-0/jahresprojekt#8]
## Short feature description:
There should be a row of filters to show or hide elements in the previews-grid based on them matching specific criteria.

## What problem shall it solve?
Find a specific element or tailoring the displayed elements to the users interests.

## Describe the solution you'd like
- On wide screens: a toggle drop-down to show the real filters
- On narrow screens: a toggled sheet or whole-width drop-down
- An indication for if a filter is active
- Forms
  - A toggle Switch (or basic dropdown toggle) for Studiengänge
  - A custom toggle grid for Kategorien
  - A dropdown for Semester in Zeit
  - A dropdown (min-max?) for publishing year in Zeit

## Additional context**
[Figma Filter](https://www.figma.com/file/Ca6Nm6XELIB63Jj7KZBz1t/Web-Design?type=design&node-id=348-6871&mode=design&t=JGtkq3jNOEZejf0j-4)

**Comment by duevil** [comment]
Why is this closed?
- [ ] Fullscreen menus on mobile are missing
- [ ] Dropdown menus on desktop are missing
- [ ] Correct filter actions need ro be implemented 
- [ ] #51 needs to be resolved
